//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Uud32.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_UUD32_DIALOG                102
#define IDS_TT_TEST                     102
#define IDS_DIS_CLEAR                   102
#define IDS_DIS_PREVIEW                 103
#define IDS_DIS_GO                      104
#define IDS_DIS_DONE                    105
#define IDD_DECODE                      106
#define IDS_DEC_CH                      106
#define IDD_ENCODE                      107
#define IDS_GETHELP                     107
#define IDS_IDCANCEL                    108
#define IDS_ABOUTBUTTON                 109
#define IDS_ENCGETHELP                  110
#define IDS_CANCEL                      111
#define IDS_NOTHING_DECODE              112
#define IDS_NOFIND_DECODE               113
#define IDS_PREVIEW                     114
#define IDS_CANCELBUTTON                115
#define IDS_GO                          116
#define IDS_BADFLS                      117
#define IDS_OOM                         118
#define IDR_MAINFRAME                   128
#define IDI_UUDICON                     130
#define IDD_DECODEOPT                   134
#define IDD_INFODIALOG                  135
#define IDI_INFOICON                    136
#define IDD_DEBUGDIALOG                 136
#define IDI_UUDEBUG                     140
#define IDB_STATUSBLOTS                 141
#define IDD_RENAMEDIALOG                142
#define IDD_LAUNCHDIALOG                144
#define IDB_ABOUT                       151
#define IDR_ACCEL                       152
#define IDC_MN_HELP                     153
#define IDI_QMARK                       154
#define IDS_DECODEGO                    306
#define IDS_DECODELIST                  307
#define IDS_TOLABEL                     308
#define IDS_DECODEPATHBROWSE            309
#define IDS_DECODEOUTPUTLIST            310
#define IDS_DECODEOPTIONS               311
#define IDS_CLEARDECODE                 312
#define IDS_ADDDECODE                   313
#define IDS_ADDCLIPBOARD                314
#define IDS_REMOVEDECODE                315
#define IDS_REMOVEDECODEOUT             316
#define IDS_RENAMEDECODEOUT             317
#define IDS_DECODEINFO                  318
#define IDS_DECINFOBOX                  319
#define IDS_INFO1                       320
#define IDS_INFO2                       321
#define IDS_UUD32ACXCTRL1               322
#define IDS_DECODEPROGRESS              323
#define IDS_DECODEPATH                  324
#define IDS_ENCODEGO                    325
#define IDS_ENCSRC                      326
#define IDS_ENCSRCBROWSE                327
#define IDS_ENCINFO                     328
#define IDS_ENCPROG                     329
#define IDS_ENC64                       330
#define IDS_ENCUU                       331
#define IDS_ENCXX                       332
#define IDS_OMFRAME                     333
#define IDS_ENCSINGLE                   334
#define IDS_ENCBRK                      335
#define IDS_ENCCLIP                     336
#define IDS_ENCLINES                    337
#define IDS_ENCDEST                     338
#define IDS_ENCPATH                     339
#define IDS_UUD32ENCODE                 340
#define IDS_FASTMODE                    341
#define IDS_DUMBMODE                    342
#define IDS_BRACKPOL                    343
#define IDS_DESP                        344
#define IDS_IGNREPLY                    345
#define IDS_OWRITEFILE                  346
#define IDS_POE                         347
#define IDS_DEBUG                       348
#define IDS_ETEXT                       349
#define IDS_DECOPTDEFAULT               350
#define IDS_DECOPTHELP                  351
#define IDS_ASSOC                       352
#define IDC_TAB2                        1005
#define IDC_ENCODEGO                    1008
#define IDC_DECODEGO                    1009
#define IDC_DECODELIST                  1010
#define IDC_DECODEPATHBROWSE            1011
#define IDC_DECODEOUTPUTLIST            1013
#define IDC_DECODEOPTIONS               1014
#define IDC_CLEARDECODE                 1015
#define IDC_DECODEPATH                  1016
#define IDC_ADDDECODE                   1017
#define IDC_ADDCLIPBOARD                1018
#define IDC_REMOVEDECODE                1019
#define IDC_REMOVEDECODEOUT             1020
#define IDC_RENAMEDECODEOUT             1021
#define IDC_DECODEINFO                  1022
#define IDC_INFO1                       1023
#define IDC_INFO2                       1024
#define IDC_ABOUTBUTTON                 1024
#define IDC_UUD32ACXCTRL1               1025
#define IDC_DECODEPROGRESS              1026
#define IDC_FASTMODE                    1028
#define IDC_DUMBMODE                    1029
#define IDC_DESP                        1030
#define IDC_IGNREPLY                    1031
#define IDC_OWRITEFILE                  1032
#define IDC_POE                         1033
#define IDC_DEBUG                       1034
#define IDC_ETEXT                       1035
#define IDC_DECOPTHELP                  1036
#define IDC_DECOPTDEFAULT               1037
#define IDC_BRACKPOL                    1038
#define IDC_INFOTITLE                   1039
#define IDC_INFOEDIT                    1040
#define IDC_INFOHELP                    1041
#define IDC_CLEARDEBUG                  1042
#define IDC_DEB2CLIP                    1043
#define IDC_INFODEBUG                   1044
#define IDC_RENSKIPBUTTON               1046
#define IDC_RENOWBUTTON                 1047
#define IDC_RENBUTTON                   1048
#define IDC_RENFILENAME                 1049
#define IDC_DEBUGCLEARBUTTON            1050
#define IDC_LAUNCHALL                   1052
#define IDC_LAUNCHHELP                  1054
#define IDC_LAUNCHBROWSE                1055
#define IDC_LAUNCHNAME                  1056
#define IDC_LAUNCHLIST                  1057
#define IDC_ENCSRC                      1060
#define IDC_ENCSRCBROWSE                1061
#define IDC_ENCINFO                     1062
#define IDC_ENCPROG                     1063
#define IDC_ENC64                       1064
#define IDC_ENCUU                       1065
#define IDC_ENCXX                       1066
#define IDC_ENCSINGLE                   1067
#define IDC_ENCBRK                      1068
#define IDC_ENCCLIP                     1069
#define IDC_ENCLINES                    1070
#define IDC_OMFRAME                     1071
#define IDC_ENCDEST                     1072
#define IDC_ENCPATH                     1073
#define IDC_UUD32ENCODE                 1074
#define IDC_DECINFOBOX                  1075
#define IDC_ASSOC                       1076
#define IDC_TOLABEL                     1077
#define IDC_ENCINFOFRAME                1078
#define IDC_LABELLINES                  1079
#define IDC_HIDETOOLTIPS                1080
#define IDC_GETHELP                     1084
#define IDC_DEC_CH                      1085
#define IDC_ENCGETHELP                  1086
#define IDC_ABOUTBMP                    1087
#define IDC_ABOUTDLL                    1090
#define IDC_SCHEMEFRAME                 1091
#define IDC_RENOUTCANCEL                1092
#define IDC_STRICT                      1093
#define IDC_OUTFMODEP                   1094
#define IDC_OUTFMODEO                   1095
#define IDC_OUTFMODEA                   1096
#define IDC_RECYCLEINP                  1097
#define IDC_ANUMBER                     1098
#define IDC_PRESERVECASE                1099
#define IDC_RENREST                     1100
#define IDC_SKIPLAUNCH                  1101
#define IDC_ENOPROMPT                   1102
#define IDC_LNOPROMPT                   1103
#define IDC_WINTEMP                     1104
#define IDC_OTHERTEMP                   1105
#define IDC_TEMPFOLDER                  1106
#define IDC_BROWSETEMP                  1107
#define IDC_DNOPROMPT                   1108
#define IDC_STRICTFILENAMES             1109
#define IDC_ENCYY                       1110

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1111
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
