/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for DECODE.hh
** Generated by RoboHELP
**
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Context Strings that are
** added to the RTF file with the same name.
**
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa.
**
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Context Strings
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define Decoding 100
#define Decoding_Example 101
#define Decoding_Details 102
#define Context_Menu_to_decode_list 103
#define Context_Menu_decode_preview_list 104
#define Launch_Box 105
#define IM_Help_Button 106
#define IM_About_Button 107
#define IM_Exit_Button 108
#define IM_Decode_Select 109
#define IM_Encode_Select 110
#define IM_Decode_These 111
#define IM_Add_Files 112
#define IM_Add_Clipboard 113
#define IM_Remove_ToDecode 114
#define IM_Decode_Info 115
#define IM_Decode_OPath 116
#define IM_Decode_OutputDir 117
#define IM_Decode_Go 118
#define IM_Decode_Options 119
#define IM_Decode_Clear 120
#define IM_Decode_Outlist 121
#define IM_DecO_Info 122
#define IM_DecO_Rename 123
#define IM_DecO_Remove 124
#define LM_Launch 125
#define LM_Using 126
#define LM_Browse 127
#define LM_Help 128
#define LM_OK 129
#define LM_OK_All 130
#define LM_Cancel 131
#define Decode_Info_Defn 133
#define Decode_Rename_Definition 134
#define Decode_Remove_Definition 135
#define Decode_Overwrite_Files 136
#define Adding_Files_To_Decode 137
#define Decode_Debug_Info 138
#define Decode_View_File_Info 139
#define Decode_Preview 140
#define IDH_UUDeview_Command_Line 141
#define IDH_Summons_help 142
