/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for ENCODE.hh
** Generated by RoboHELP
**
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Context Strings that are
** added to the RTF file with the same name.
**
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa.
**
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Context Strings
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define Encoding 300
#define Encoding_Details 301
#define EM_EncodeFile 302
#define EM_EncodeBrowse 303
#define EM_Info 304
#define EM_Base64 305
#define EM_UU 306
#define EM_XX 307
#define EM_Go 308
#define EM_Single 309
#define EM_Break 310
#define EM_Clipboard 311
#define EM_Output 312
#define EM_Browse_Out 313
#define Encode_Context 314

