/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for UUD16.hh
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Context Strings that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Context Strings
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define IDH_CONTENTS 1
#define What_is_UUDeview 2
#define Introduction_to_Decoding 3
#define UUDeview_DLL 4
#define Revision_History 5
#define FAQ_No_GO_Button 6
#define FAQ_encoding_MIME_and_e_mail 7
#define FAQ_Decoding_Problem_Files 10
#define Contacting_the_Authors 11
#define GNU_General_Public_License 12
