/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for Methods.hh
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define H_METHODS 901
#define IDH_ClipboardFile_Method 902
#define IDH_CRC32_Method 903
#define IDH_DFileTo_Method 904
#define IDH_DLoad_Method 905
#define IDH_DRemove_Method 906
#define IDH_Encode_Method 907
#define IDH_FileFilter_Method 908
#define IDH_QuickDecode_Method 909
#define IDH_Reset_Method 910
#define IDH_XFileAdd_Method 911
#define IDH_XFileDel_Method 912
#define IDH_Return_type 913
#define IDH_Uud32acx_Methods 914
#define ClipFileOperations_Constants 915
#define Encoding_Modes 916
#define Header_Styles_Constants 917
#define IDH_GetLastError_Method 918
