/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for Properties.hh
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define H_PROPERTIES 500
#define Bracket_Policy_Property 501
#define Desperate_Mode_Property 502
#define DFCount_Property 503
#define DFile_Property 504
#define DFileDetail_Property 505
#define DFileFlags_Property 506
#define DFileInfo_Property 507
#define DFileStatus_Property 508
#define Dumb_Mode_Property 509
#define Fast_Mode_Property 510
#define Ignore_Reply_Property 511
#define Last_Message_Property 512
#define Library_Version_Property 513
#define Output_Path_Property 514
#define Overwrite_Property 515
#define Verbose_Property 516
#define X_File_Auto_Property 517
#define XFile_Property 518
#define XFileCount_Property 519
#define Property_Return_Type 520
#define Design_Time_Property 521
#define Run_Time_Property 522
#define Persistent_Property 523
#define Read_Only_Property 524
#define IDH_Property_List 525
#define DFileDetail_Constants 526
#define DFileStatus_Constants 527
#define IDH_UseText_Property 528
#define StrictMIME_Property 529
#define RemoveAfter_Property 530
