/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for UUD32ACX.hh
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define GNU_General_Public_License 2
#define H_Contents 4
#define H_Overview 5
#define H_Decoding 6
#define H_ENCODING 7
#define H_QUICK 8
#define H_XFILES 9
#define H_RETCODE 12
#define H_AUTHORS 13
#define IDH_Constants 14
